### PR TITLE
refactor: use new `@metamask/keyring-api` layout (split packages)

### PR DESCRIPTION
**Pull request by ccharly**
## Explanation

The `keyring-api` has been split out into multiple smaller packages, this introduce some breaking changes since some exports have been moved elsewhere.

This was done to reduce the number of required dependencies for the `keyring-api`. The `InternalAccount` type (widely used internally by some controllers) has been moved to a new package: `@metamask/keyring-internal-api`.

## References

Relates to:
- https://github.com/MetaMask/accounts/pull/24

Basic testing done through the CI + preview builds:
- https://github.com/MetaMask/metamask-extension/pull/28861

### `@metamask/keyring-controller`

- **CHANGED**: Remove use of peer dependency `@metamask/providers`
- **CHANGED**: Bump `@metamask/keyring-api` to `^12.0.0`
- **CHANGED**: Use `@metamask/keyring-internal-api@^1.0.0`

> Even if we are bumping the major of the `keyring-api`, this is not breaking since all
> types from the split are compatible. The only difference now here is the `Keyring`
> interface which has a new optional method `listAccountTransactions`, optional, thus
> non-breaking (and this type is not used there anyway)

### `@metamask/accounts-controller`

- **CHANGED**: Bump `@metamask/keyring-api` to `^12.0.0`
- **CHANGED**: Bump `@metamask/eth-snap-keyring` to `^7.0.0`
- **CHANGED**: Use `@metamask/keyring-internal-api@^1.0.0`

> `eth-snap-keyring` has been bumped to `7.0.0` but this was a mistake since no breaking changes has been introduced there either.
> The version `6.0.0` also introduces `ts-bridge` builds, but this is already compatible with this repo, so not breaking here either.

### `@metamask/assets-controllers`

- **CHANGED**: Remove use of `@metamask/keyring-api`
- **CHANGED**: Use `@metamask/keyring-internal-api@^1.0.0`

### `@metamask/chain-controller`

- **CHANGED**: Remove use of `@metamask/keyring-api`
- **CHANGED**: Use `@metamask/keyring-internal-api@^1.0.0`
- **CHANGED**: Use `@metamask/keyring-utils@^1.0.0`

### `@metamask/profile-sync-controller`

- **CHANGED**: Remove use of `@metamask/keyring-api`
- **CHANGED**: Use `@metamask/keyring-internal-api@^1.0.0`

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by ccharly** [comment]
@metamaskbot publish-preview

**Comment by ccharly** [comment]
@metamaskbot publish-preview

**Comment by ccharly** [comment]
@metamaskbot publish-preview

**Comment by ccharly** [comment]
@metamaskbot publish-preview

**Comment by ccharly** [comment]
@metamaskbot publish-preview

**Comment by ccharly** [comment]
@metamaskbot publish-preview

**Comment by ccharly** [comment]
@metamaskbot publish-preview

**Review by mirceanis — APPROVED** [review]
looks ok to me

**Review by Prithpal-Sooriya — APPROVED** [review]

**Review by sahar-fehri — APPROVED** [review]

**Review by gantunesr — APPROVED** [review]

**Pull request merged**
