### PR TITLE
Preserve provider during lookupNetwork

### PR DESCRIPTION
**Pull request by mcmire**
## Description

If the network is switched while `lookupNetwork` is awaiting the request for `net_version`, then the subsequent request for `eth_getBlockByNumber` will take place against the new network, not the original one. Despite the fact that this won't matter soon, as we will shortly make it so that `lookupNetwork` won't make any state changes if it detect a network change, it is quite confusing when debugging tests that involve network switching in general (a future commit will introduce logging so that such debugging is more possible). For this reason, this commit changes `lookupNetwork` so that it stores a reference to the provider (not the provider proxy) before doing anything and passes that provider to the methods responsible for making requests. This also means that we can't reuse `this.#ethQuery` in these methods, as it relies on the provider proxy; we must make a new instance of EthQuery before making the request. (This also raises a question about the efficacy of the proxy, but that is a topic for another day.)

## Changes

There should be no user-facing changes.

## References

Relates to https://github.com/MetaMask/core/pull/1375.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation for new or updated code as appropriate (note: this will usually be JSDoc)
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by Gudahtt** [comment]
>If the network is switched while `lookupNetwork` is awaiting the request for `net_version`, then the subsequent request for `eth_getBlockByNumber` will take place against the new network, not the original one

I'm having trouble following how this would be possible. The `net_version` request will of course come first, but the `eth_getBlockByNumber` request should be dispatched _synchronously_ after the `net_version` call, since there's no `await` between those steps. It should be impossible to switch networks in between those two actions.

**Comment by mcmire** [comment]
> I'm having trouble following how this would be possible. The `net_version` request will of course come first, but the `eth_getBlockByNumber` request should be dispatched synchronously after the `net_version` call, since there's no await between those steps. It should be impossible to switch networks in between those two actions.

Hmm, maybe I did a poor job of explaining this. It's less that the network can be switched after `net_version` resolves but before `eth_getBlockByNumber` starts, but that it can be switched after `net_version` is started but before it's completed, i.e., while the request is taking place. Same goes for `eth_getBlockByNumber`.

**Comment by Gudahtt** [comment]
Hmm, OK, that makes sense but I'm still not sure I follow what the problem being addressed is. How did that end up having a negative impact? If the provider was set to the correct network when the calls were dispatched, I'd expect this to work correctly.

**Comment by mcmire** [comment]
After discussion, we determined that this was a lower priority PR to merge. I'll keep it open for now to keep the discussion going, but I may end up closing it later.

**Comment by mcmire** [comment]
I'll close this since we decided this isn't necessary.

**Pull request closed without merging**
