### PR TITLE
Use Set to improve lookup performance

### PR DESCRIPTION
**Pull request by Cal-L**
**Improve lookup time in PhishingController**

This PR creates a Set from `metamaskConfig.blocklist` in the `PhishingController`. The blocklist Set is later used as a lookup inside of a filter method. As a result, look up performance is significantly improved by using a `Set` + `has` method instead of `includes` method from an Array.

**Description**

_Itemize the changes you have made into the categories below_

- CHANGED:

  - `PhishingController.updatePhishingLists`
    - Create a `Set` from `metamaskConfig.blocklist` to be used as lookup.

**Checklist**

- [x] Tests are included if applicable
- [x] Any added code is fully documented

**Issue**

Resolves https://github.com/metamask/metamask-mobile/issues/5382

### CODE REVIEW

**Comment by mcmire** [comment]
I'm assuming by the description that this was slow in some cases before? If so, what were those cases, and how fast does this make this operation — or if you don't know then how does it improve the UX?

**Review by gantunesr — APPROVED** [review]
LGTM

**Comment by gantunesr** [comment]
Hey @mcmire! In the mobile PR @cortisiko did some performance tests to verify this. I'll leave here the comment,

> _We should expect cold start times on iOS to be ~4seconds, while Android (depending on device) shouldn't take more than 10 seconds. (Both times reported by Curtis). Relative to the previous app version, the cold start up times should be noticeably lower._

https://github.com/MetaMask/metamask-mobile/pull/5641

**Comment by gantunesr** [comment]
From what I see in the app, this is getting used in a callback for each WebView tab the app has (method: `isAllowedUrl`).

https://github.com/MetaMask/metamask-mobile/blob/8690260f43383a9458a27b169e5211ce6d940359/app/components/Views/BrowserTab/index.js#L965

**Review by mcmire — APPROVED** [review]
Thanks @gantunesr for the context! LGTM.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by Gudahtt** [comment]
@Mrtenz I believe mobile is using JavaScriptCore for their engine at the moment? (not 100% sure). If so, it may have different performance characteristics. Some of the devices used may have slow CPUs as well. I agree that it's a surprising result though.

**Comment by gantunesr** [comment]
@Gudahtt @Mrtenz 

Just to confirm, it is JavaScriptCore. Hopefully we can upgrade RN this year and use the new JS engine for better performance

**Comment by Mrtenz** [comment]
Makes sense!

**Pull request merged**
