### PR TITLE
fix: update subpath exports to use new .d.cts definition files.

### PR DESCRIPTION
**Pull request by Prithpal-Sooriya**
## Explanation

We have moved from tsup to ts-bridge, which generates a different path/file for typescript definition files.

This updates the notifications team packages that use subpath exports:
- `@metamask/profile-sync-controller`
- `@metamask/notification-services-controller`

## References

https://consensyssoftware.atlassian.net/browse/NOTIFY-1108

### `@metamask/profile-sync-controller`

- **CHANGED**: Subpath exports `"types"` files.
- **ADDED**: SDK to supported `"files"` in package.json

### `@metamask/notification-services-controller`

- **CHANGED**: Subpath exports `"types"` files.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by Prithpal-Sooriya** [comment]
@metamaskbot publish-preview

**Review by Mrtenz — APPROVED** [review]
Looks good! Sorry about this, I missed it in my PR.

**Comment by Prithpal-Sooriya** [comment]
OK tested this on extension, this is valid. Will merge :)

**Review by matteoscurati — APPROVED** [review]
LGTM

**Pull request merged**
