### PR TITLE
Bump min Node version to 18.18; use LTS for dev

### PR DESCRIPTION
**Pull request by mcmire**
## Explanation

Now that both extension and mobile are using Node 18, we can follow suit.

### For all packages

- **BREAKING:** Bump minimum Node version to 18.18

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by mcmire** [comment]
Note that this would require major versions for everything all over again, so there's no immediate urgency to merge this, but I want to go ahead and start the conversation :)

**Comment by mcmire** [comment]
Setting this to draft in the meantime.

**Comment by mcmire** [comment]
I've created tickets for the above repos. MetaMask Desktop has been put on ice, so I don't think we have to worry about that right now.

**Comment by Gudahtt** [comment]
Shouldn't we bump the minimum version here first, before bumping the dependencies? We'd want to increase the minimum from the bottom-up, starting at the clients, then here, then to dependencies. Otherwise v16 support will effectively be dropped here prior to the supported range changing.

**Comment by mcmire** [comment]
@Gudahtt I think what @legobeat is saying is that there are some packages in this repo that are dependencies of the repos he named. So we'd want to bump the packages there first, otherwise if we bump the packages here, then it forces us to bump those if we need to upgrade one of these packages.

**Comment by Gudahtt** [comment]
Oh I see, sorry I misunderstood. That list is for projects depending on this repository, similar to extension/mobile, so yes we'd want to update those first.

**Comment by mcmire** [comment]
@Gudahtt I think what @legobeat is saying is that the packages he linked to depend on some packages in the core monorepo, i.e., the core packages are the dependencies.

**Comment by mcmire** [comment]
I've updated this PR so that it is ready to go when we merge https://github.com/MetaMask/smart-transactions-controller/issues/249.

**Comment by mcmire** [comment]
I've merged in changes from `main` and fixed lint violations. Ready for review again.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Comment by MajorLift** [comment]
In other packages we've been using `"^18.18 || >=20"` instead of `">=18.18 || >=20"` in the `engines` field and yarn constraints. Are we purposefully going for a stronger constraint in core?

**Comment by mcmire** [comment]
@MajorLift No, this was just an oversight 🤦🏻 I've fixed the versions to actually follow the module template.

**Review by MajorLift — APPROVED** [review]
LGTM!

**Comment by mcmire** [comment]
@Gudahtt mentioned that we may want to merge https://github.com/MetaMask/core/pull/3908 before merging this PR. Adding `DO-NOT-MERGE` in the meantime.

**Comment by mcmire** [comment]
This branch became stale, so I rebased it against the latest changes in `main`, and squashed all of the commits.

Merging this will kick off another round of breaking changes. Feel free to approve this, but we will see if we can pair this with some other breaking changes that we want to make anyway.

**Review by legobeat — DISMISSED** [review]

**Comment by mcmire** [comment]
Update on this PR: This is something that we still want to do, but we are waiting until we finish some fixes we want to make to the keyring controller, and I am also heads down on work to support multichain for the next few weeks or so. After we get through those, though, I can start the process to merge this PR and cut new major releases for everything.

**Review by cryptodev-2s — APPROVED** [review]
LGTM!

**Review by dbrans — APPROVED** [review]

**Review by Mrtenz — APPROVED** [review]

**Pull request merged**
