### PR TITLE
fix: Some wallet_switchEthereumChain calls queued incorrectly

### PR DESCRIPTION
**Pull request by BelfordZ**
## Explanation

`eth_requestAccounts` is a confirmation method only when there exists no permission yet for the given domain. This requires the request to be queued. We have not optimized the queueing to check if there exists a permission before deciding to enqueue calls to `eth_requestAccounts`, though that is an optimization we could make in the future and is outside the scope of this PR. 

This PR will no longer require the wallet to be on the correct network before the eth_requestAccounts call is made. As an alternative, we could still require that the user be on the correct chain, but only if there is no permission yet.

## References

fixes https://github.com/MetaMask/MetaMask-planning/issues/2186

### `@metamask/queued-request-controller`

- **FIXED**: `eth_requestAccounts` should not check to switch chain first

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by adonesky1** [comment]
@metamaskbot publish-preview

**Comment by Gudahtt** [comment]
Was #2186 the correct issue to link? That issue seems to be about a different case (the repro instructions start with you connected already to both dapps)

**Comment by BelfordZ** [comment]
@Gudahtt yes

**Review by mcmire — COMMENTED** [review]
Are there any tests we can write to confirm this fix is working as intended?

**Comment by BelfordZ** [comment]
@mcmire for sure! Are you thinking something along the lines of: 

```
it(' does not require `eth_requestAccounts` calls to switch network before handling', () => { ... })
```

That said, we should prolly either do this ontop of https://github.com/MetaMask/core/pull/3781 (or on `main` once merged).

**Pull request closed without merging**
