### PR TITLE
Release 69.0.0

### PR DESCRIPTION
**Pull request by mcmire**
See changelogs.

### CODE REVIEW

**Comment by mcmire** [comment]
Looks like some types got added in https://github.com/MetaMask/core/pull/1554. I can add these to the transaction controller changelog after standup.

**Comment by adonesky1** [comment]
> @adonesky1
[Merge branch 'main' into release/69.0.0](https://github.com/MetaMask/core/pull/1565/commits/d79a9c085c167029070ed1e63619a2d0f9ccb477)

The commit added here included no public facing changes: https://github.com/MetaMask/core/pull/1554

**Review by adonesky1 — CHANGES_REQUESTED** [review]
@mcmire yep! Lets add those types

**Comment by mcmire** [comment]
It looks like the EtherscanTransactionMeta type was accidentally made private in https://github.com/MetaMask/core/pull/1554. I've re-exposed this type in https://github.com/MetaMask/core/pull/1567 to prevent a breaking change. Once we have that merged, then this PR is good to go.

**Review by adonesky1 — APPROVED** [review]

**Comment by Gudahtt** [comment]
@metamaskbot publish-preview

**Pull request merged**
