### PR TITLE
feat: remove global network from signature controller

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## Explanation

Remove all global network usage from the signature controller to support multi-chain in the clients.

Specifically:

- Remove `getCurrentChainId` constructor callback from `SignatureController`.
- Determine `chainId` using `networkClientId` from `request` argument and `NetworkController` messenger action.
- Persist `chainId` and `networkClientId` in state.

## References

Fixes [#3498](https://github.com/MetaMask/MetaMask-planning/issues/3498)

[Extension Adoption](https://github.com/MetaMask/metamask-extension/pull/28063)
[Mobile Adoption](https://github.com/MetaMask/metamask-mobile/pull/11996)

### `@metamask/signature-controller`

- **BREAKING**: Make `request` argument required in `newUnsignedPersonalMessage` and `newUnsignedTypedMessage` methods.
- **ADDED**: Add `chainId` and `networkClientId` to `SignatureRequest` and `LegacyMessage` types.
- **CHANGED**: Throw if no `networkClientId` provided or if `chainId` cannot be determined.
- **REMOVED**: Remove `getCurrentChainId` and `getAllState` callbacks from constructor options.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate
- [x] I've prepared draft pull requests for clients and consumer packages to resolve any breaking changes

### CODE REVIEW

**Comment by matthewwalsh0** [comment]
@metamaskbot publish-preview

**Review by cryptodev-2s — DISMISSED** [review]
LGTM!

**Comment by matthewwalsh0** [comment]
@metamaskbot publish-preview

**Review by jpuri — APPROVED** [review]
Looks good 👍

**Pull request merged**
