### PR TITLE
Move composable-controller utility types to base-controller

### PR DESCRIPTION
**Pull request by MajorLift**
## Explanation

This commit moves `BaseController`-related types and functions in `@metamask/composable-controller` to `@metamask/base-controller`.

Because applying these changes requires a concurrent major update of `@metamask/base-controller`, this commit will be excluded from `@metamask/composable-controller@8.0.0` (https://github.com/MetaMask/core/pull/4467), so that complications can be avoided while applying `8.0.0` to mobile.

## References

- Blocked by https://github.com/MetaMask/core/pull/4467
- Blocked by https://github.com/MetaMask/metamask-mobile/pull/10441

### Added

- Migrate from `@metamask/composable-controller@8.0.0` into `@metamask/base-controller`: types `LegacyControllerStateConstraint`, `RestrictedControllerMessengerConstraint` and type guard functions `isBaseController`, `isBaseControllerV1`  ([#4581](https://github.com/MetaMask/core/pull/4581))
- Add and export types `ControllerInstance`, `BaseControllerInstance`, `StateDeriverConstraint`, `StateMetadataConstraint`, `StatePropertyMetadataConstraint`, `BaseControllerV1Instance`, `ConfigConstraintV1`, `StateConstraintV1` ([#4581](https://github.com/MetaMask/core/pull/4581))

### Removed

- **BREAKING:** Remove exports for types `LegacyControllerStateConstraint`, `RestrictedControllerMessengerConstraint`, and type guard functions `isBaseController`, `isBaseControllerV1` ([#4467](https://github.com/MetaMask/core/pull/4467))
  - These have been migrated to `@metamask/base-controller@6.2.0`.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by MajorLift** [comment]
@metamaskbot publish-preview

**Comment by MajorLift** [comment]
@metamaskbot publish-preview

**Comment by MajorLift** [comment]
@metamaskbot publish-preview

**Comment by MajorLift** [comment]
@metamaskbot publish-preview

**Comment by MajorLift** [comment]
@metamaskbot publish-preview

**Comment by MajorLift** [comment]
@metamaskbot publish-preview

**Review by mikesposito — APPROVED** [review]
LGTM!

**Pull request merged**
