### PR TITLE
Update controllers that rely on provider to listen to `NetworkController:networkDidChange` instead of `NetworkController:stateChange`

### PR DESCRIPTION
**Pull request by jiexi**
## Explanation

Listening to `NetworkController:stateChange` to catch network changes doesn't guarantee that the provider proxy has also been updated to point to the new network. `NetworkController:networkDidChange` does however. This PR updates several controllers that rely on the provider proxy to listen to `NetworkController:networkDidChange` rather than `NetworkController:stateChange`. GasFeeController and AssetsContractController are already listening to `NetworkController:networkDidChange` on the extension side despite their constructor param hook names still being `onNetworkStateChange` (which this PR also renames to be correct)

## References

* See https://github.com/MetaMask/MetaMask-planning/issues/1713

### `@metamask/assets-controllers`

- **BREAKING**: `TokensController` constructor params `onNetworkStateChange` replaced with `onNetworkDidChange`
- **BREAKING**: `AssetsContractController` constructor params `onNetworkStateChange` replaced with `onNetworkDidChange`

### `@metamask/ens-controller`

- **BREAKING**: `EnsController` constructor params `onNetworkStateChange` replaced with `onNetworkDidChange`

### `@metamask/gas-fee-controller`

- **BREAKING**: `GasFeeController` will subscribe to `NetworkController:networkDidChange` now instead of `NetworkController:stateChange` using the passed in `messenger` param when `onNetworkDidChange` is not provided
- **CHANGED**: `GasFeeController` constructor params optional `onNetworkStateChange` replaced with optional `onNetworkDidChange`

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Review by adonesky1 — COMMENTED** [review]
Looks right to me! Would love to get @mcmire or @Gudahtt to approve before we merge though.

**Comment by BelfordZ** [comment]
Looks good, should get a great performance improvement from this approach. Let's make sure to test the 'infura blocked' (or anything other network change errors) - These controllers will no longer have event handlers called when there is an error in switching the network.

**Review by BelfordZ — APPROVED** [review]

**Comment by jiexi** [comment]
> Let's make sure to test the 'infura blocked' (or anything other network change errors) - These controllers will no longer have event handlers called when there is an error in switching the network.

State updates from the network metadata flow would follow soon after a `networkDidChange` event. We definitely would be firing the listener one less time when migrating away from `stateChange`, but I don't believe this will cause any regression in functionality. Thank you for pointing this out!

**Review by mcmire — APPROVED** [review]
Makes sense to me!

**Comment by jiexi** [comment]
@metamaskbot publish-preview

**Pull request merged**
