### PR TITLE
Re-enable import/no-named-as-default-member

### LINKED ISSUE #1924: Re-enable `import/no-named-as-default-member`
This rule seems to have been disabled for convenience. We don't need to do this, however, and can honor this rule instead.

### PR DESCRIPTION
**Pull request by mcmire**
## Explanation

We don't need to disable this rule; we can honor it instead.

## References

Fixes #1924.

## Changelog

(No consumer-facing changes)

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by MajorLift** [comment]
How do we feel about `import * as sinon from 'sinon';`? It's covered by the rule `import/no-namespace`.

There are quite a few `sinon`, `uuid` methods that are being used in the exact same form (`sinon.<method>`) as the calls being fixed in this PR. 

I could add a ticket for this and put it in my backlog. It looks like we could enable `import/no-namespace` with a few regex-replaces.

**Review by MajorLift — DISMISSED** [review]
Looks good!

**Comment by mcmire** [comment]
Er, yes, using `sinon.useFakeTimers` (or whatever it happens to be) would be a better approach than importing the named exports in this case. Maybe I should update this PR to use that style.

**Comment by mcmire** [comment]
> How do we feel about `import * as sinon from 'sinon';`? It's covered by the rule `import/no-namespace`.
> 
> There are quite a few `sinon`, `uuid` methods that are being used in the exact same form (`sinon.<method>`) as the calls being fixed in this PR.
> 
> I could add a ticket for this and put it in my backlog. It looks like we could enable `import/no-namespace` with a few regex-replaces.

`no-namespace` seems to forbid the kind of import that you suggested. I'm okay with using that style. We already use it in the `core` repo, I just forgot :) So no need to put it on your backlog.

**Comment by mcmire** [comment]
@MajorLift I updated the PR following your comments. Do they make sense?

**Review by MajorLift — APPROVED** [review]
Yes I like this better since it's consistent with the current usage in the codebase.

If we ever write documentation around eslint rules, we could mention that there are two options for fixing default imports, and that we prefer namespace import for some cases (`sinon`, `uuid`, internal packages, ...):
- namespace import: `import * as name from "module-name"`
- named imports: `import { export1, export2 } from "module-name"`

**Comment by mcmire** [comment]
@MajorLift Sounds good!

**Pull request merged**
