### PR TITLE
deps(keyring-controller): @metamask/keyring-api@^2.0.0->^3.0.0

### PR DESCRIPTION
**Pull request by legobeat**
#### Blocking
- https://github.com/MetaMask/metamask-extension/pull/21934

### `@metamask/keyring-controller`

- **CHANGED**: Update `@metamask/keyring-api` from `^2.0.0` to `^3.0.0`
- **CHANGED**: Update `@metamask/eth-keyring-controller` from `^17.0.0` to `^17.0.1`

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by mikesposito** [comment]
@SocketSecurity ignore @metamask/obs-store@9.0.0
 
[gudahtt](https://socket.dev/npm/user/gudahtt) is a trusted author

    @SocketSecurity ignore @metamask/eth-keyring-controller@16.0.0
    
v16.0.0 has been published [4 days ago](https://www.npmjs.com/package/@metamask/eth-keyring-controller)

**Comment by mcmire** [comment]
@mikesposito This is blocked by the fact that `keyring-api` introduces a circular dependency on this repo, correct?

**Comment by mikesposito** [comment]
@mcmire Exactly, we should fix that in `eth-keyring-controller` before merging this one

**Comment by mikesposito** [comment]
We should now update to `eth-keyring-controller` ^17.0.1 directly, but v17 comes with a breaking change related to `createNewVaultAndKeychain` and `createNewVaultAndRestore`.

**Pull request closed without merging**
