### PR TITLE
Add getNetworkConfigurationByNetworkClientId

### LINKED ISSUE #2019: [network-controller] Add a `getNetworkConfiguration` action
There is currently no easy way for a controller to access the user-provided metadata for a known network (nickname, ticker, etc.). If it's for a custom network, then it can use a messenger to get the set of network configurations from the network controller, then look up a network configuration that matches the same information. If it's for an Infura network, then it can use the `BUILT_IN_NETWORKS` constant (or other constants).

We can hide this inconvenience by creating a `getNetworkConfiguration` method and action that other controllers can then call directly.

### PR DESCRIPTION
**Pull request by mcmire**
## Explanation

Currently, if you have the ID of a network client for a custom network and you want to get information like the ticker or nickname for that network, you have to have a reference to the network controller so you can look up that network client ID in the list of network configurations. It's very roundabout, and we can do better.

This commit introduces a method on NetworkController, `getNetworkConfigurationByNetworkClientId`, that can be used to retrieve the network configuration that corresponds to a custom network given a network client ID. Although the concept of a network configuration was created for custom networks, this method also works for a built-in network client ID by constructing a "fake" network configuration.

This commit also introduces a controller action so that the network controller instance is not needed in order to call this method.

## References

Fixes #2019.

## Changelog

(Changelog entries included with this PR)

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by MajorLift** [comment]
Jest coverage thresholds can be raised:

```diff
diff --git a/packages/network-controller/jest.config.js b/packages/network-controller/jest.config.js
index 985e7a447..ce4f8681c 100644
--- a/packages/network-controller/jest.config.js
+++ b/packages/network-controller/jest.config.js
@@ -17,10 +17,10 @@ module.exports = merge(baseConfig, {
   // An object that configures minimum threshold enforcement for coverage results
   coverageThreshold: {
     global: {
-      branches: 71.11,
-      functions: 78.57,
-      lines: 85.1,
-      statements: 85.1,
+      branches: 76.27,
+      functions: 95,
+      lines: 92.09,
+      statements: 91.68,
     },
   },
 
```

**Review by MajorLift — DISMISSED** [review]
LGTM

**Comment by mcmire** [comment]
@MajorLift  Merge conflicts resolved and coverage thresholds bumped. Can I get another review?

**Review by MajorLift — APPROVED** [review]
Looks good!

**Pull request merged**
