### PR TITLE
Release 70.0.0

### PR DESCRIPTION
**Pull request by mikesposito**
See changelogs.

### CODE REVIEW

**Comment by mikesposito** [comment]
@jpuri I'm having difficulties finding a PR related to the release you were preparing for `@metamask/signature-controller`. Should this be actually released, or should be excluded?

**Review by cryptodev-2s — DISMISSED** [review]
LGTM!

**Comment by mikesposito** [comment]
Looking at this discussion: https://github.com/MetaMask/core/pull/1568
Looks like we can remove `@metamask/signature-controller` for now.

**Review by cryptodev-2s — DISMISSED** [review]
LGTM!

**Comment by adonesky1** [comment]
@mikesposito could we pull this commit that was just merged into the release: https://github.com/MetaMask/core/commit/f89db77fb7afd4be913c7d026d64dc86f0a42eac ?

**Review by adonesky1 — CHANGES_REQUESTED** [review]
@mikesposito could we pull this commit that was just merged into the release: https://github.com/MetaMask/core/commit/f89db77fb7afd4be913c7d026d64dc86f0a42eac ?

**Comment by mcmire** [comment]
I've added a new changelog entry for the change that was just merged and will approve this PR so we can get it merged tomorrow.

**Review by mcmire — APPROVED** [review]

**Comment by mcmire** [comment]
Merging this to unblock the DevX team.

**Comment by Gudahtt** [comment]
@metamaskbot publish-preview

**Pull request merged**
