### PR TITLE
Update root README dependency graph with `eth-json-rpc-provider` and changes from recent releases

### PR DESCRIPTION
**Pull request by MajorLift**
## Explanation

- Updating root README to include @metamask/eth-json-rpc-provider.
- Updating dependency graph to reflect changes made between releases v78.0.0 through v81.0.0.

## References

- See https://github.com/MetaMask/core/pull/1738

### `core`

- **CHANGED**: Updated README dependency graph.

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Review by mcmire — COMMENTED** [review]
Do we also want to add `eth-json-rpc-provider` to the list of packages above the graph? (This list isn't autogenerated — yet 😄 )

**Comment by MajorLift** [comment]
Good catch! Totally missed that.

**Comment by MajorLift** [comment]
Found more missing modules in that list. Adding them now..

**Review by mcmire — APPROVED** [review]
Looks good!

**Pull request merged**
