### PR TITLE
Update @metamask/eth-json-rpc-middleware in network controller

### PR DESCRIPTION
**Pull request by jpuri**
## Explanation
Update dependency `@metamask/eth-json-rpc-middleware` in network controller.

## References
MetaMask/MetaMask-planning#1461

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Review by cryptodev-2s — APPROVED** [review]
LGTM!

**Comment by jpuri** [comment]
@SocketSecurity ignore @metamask/eth-json-rpc-middleware@12.0.1

**Comment by mcmire** [comment]
For context, this bump includes the following fix, as well as some dependency updates: https://github.com/MetaMask/eth-json-rpc-middleware/pull/263

**Review by mcmire — APPROVED** [review]
Looks good!

**Pull request merged**
