### PR TITLE
Add Paradigm hotlist

### PR DESCRIPTION
**Pull request by samczsun-paradigm**
**PR Title**

Add Paradigm hotlist

**Description**

Adds the Paradigm hotlist to the list of phishing endpoints to check. This hotlist will be updated manually during security incidents, almost always by me personally.

- ADDED:

  - New endpoint to PhishingController

**Checklist**

- [x] Tests are included if applicable
- [x] Any added code is fully documented

### CODE REVIEW

**Comment by FrederikBolding** [comment]
Thanks for the PR, Sam! I added some tests and fixed some linting issues making it ready for review!

I wonder if we would prefer the Paradigm hotlist only including `blacklist`, similarly to the Phishfort list 🤔 

cc @Gudahtt @409H

**Comment by samczsun-paradigm** [comment]
Thanks! Was meaning to get to the failing tests after I pushed out the project I was working on, but I see it probably would've taken a bit of time without any context.

I'm open to only including the blacklist if that would make things easier.

**Comment by Gudahtt** [comment]
I agree with @FrederikBolding ; that would be much easier for us to manage. The fuzzylist has a high false-positive rate so we have to be very careful about expanding that.

Also, where should we direct users that want to dispute an entry on your list? We include a dispute link on our warning page, so we need one for each link. We use our `eth-phishing-detect` repo for disputes, and drop them straight into a partially-filled-out issue template. But a "contact" page or something would work too.

**Comment by samczsun-paradigm** [comment]
Updated. As for the redirect link, maybe the [issues page](https://github.com/paradigmxyz/phishing-list/issues) too then.

**Comment by samczsun-paradigm** [comment]
Ah, that lint took a long time to fail. Will check it out

**Comment by FrederikBolding** [comment]
@samczsun-paradigm Looks like this needs a rebase after some changes were made to the PhishingController.

**Pull request closed without merging**
