### PR TITLE
[base-controller] Narrow return types of `get{Anonymized,Persistent}State`

### LINKED ISSUE #3962: [base-controller] Consistently apply `Record<string, Json>` constraint on BaseControllerV2 state objects and types
There are some key `BaseControllerV2` types where the state type is not constrained with `Record<string, Json>`. This constraint should be applied consistently across the codebase.

### PR DESCRIPTION
**Pull request by MajorLift**
## Explanation

#3949 narrows the return type of the `deriveStateFromMetadata` function from `Record<string, Json>` to `Record<keyof ControllerState, Json>`. However, the resulting changes to functions `getAnonymizedState` and `getPersistentState` weren't reflected in that PR. 

This commit fixes the return type annotations for these functions to the correct type: `Record<keyof ControllerState, Json>`.

## References

- Closes #3962
- Follows from #3949

#### Changed

- **BREAKING:** Narrow the return types of functions `getAnonymizedState<ControllerState>` and `getPersistentState<ControllerState>` from `Record<string, Json>` to `Record<keyof ControllerState, Json>`. ([#3949](https://github.com/MetaMask/core/pull/3949), [#4040](https://github.com/MetaMask/core/pull/4040))

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by Gudahtt** [comment]
Why was `deriveStateFromMetadata` narrowed in the first place? That was intentionally not narrowed, because we might want to derive state with different keys than the real controller state.

e.g. `{ address: '0x....' }` => `{ maskedAddress: '0x...' }

**Comment by MajorLift** [comment]
With how `deriveStateFromMetadata` is written, it looks like it's impossible for its return object to contain a key that is not already in `keyof typeof state`. Do you mean that the function should be able to handle `state` or `ControllerState` input that is wider than actual controller state? 

If that's true, I don't think there should be any issues with narrowing the return object's index signature from `string` to `keyof ControllerState`, as long as the function can be called with a wider `ControllerState` type.

**Comment by Gudahtt** [comment]
Oh you're right, sorry I forgot, the flexibility there is only on the sub-property level. This does make sense in that case.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
