### PR TITLE
Add `ticker` to `NetworkClientConfiguration`

### PR DESCRIPTION
**Pull request by jiexi**
## Explanation

Adds `ticker` to `NetworkClientConfiguration`. Needed for multichain work on the CurrencyRateController which relies on going from networkClientId to ticker value which would not be possible without these changes.

## References

See https://github.com/MetaMask/MetaMask-planning/issues/1025

### `@metamask/network-controller`

- **BREAKING**: Add `ticker` to `NetworkClientConfiguration`
- **ADDED**: In `upsertNetworkConfiguration()`, populate the stored `NetworkClientConfiguration.ticker` from passed in `networkConfiguration` value

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Review by mcmire — COMMENTED** [review]
This is fine as a short term fix, but it goes against the purpose of the the network client configuration, which is to hold configuration data that we need to instantiate a stack of middleware. The ticker is not used anywhere in the middleware stack as it's a user-facing piece of data. If this solves the problem now, okay, but we will want to remove this later after we come up with the abstraction around a network that we _really_ want.

**Review by mcmire — APPROVED** [review]
Looks good. Would this be a breaking change for `network-controller` specifically, since it exports NetworkClientConfiguration?

**Comment by jiexi** [comment]
Indeed it is breaking since it's not an optional field. I'll update the PR desc

**Comment by jiexi** [comment]
@metamaskbot publish-preview

**Pull request merged**
