### PR TITLE
fix: NFT detection running too many times

### PR DESCRIPTION
**Pull request by bergeron**
## Explanation

The `NftDetectionController` was making unnecessary HTTP requests.

(1) It was fetching NFTs when any setting changes:

https://github.com/MetaMask/core/assets/3500406/297b1889-ee17-4c57-890b-8f94e4b1be4b

(2) When each polling interval arrives, it can send ~7 identical requests instead of 1.  See timeline:

Screenshot 2024-02-13 at 6 08 53 PM

(3) one redundant request when switching accounts

All come from `onPreferencesStateChange` triggering a re-start.

(2)  happens because it fires ~7 times on startup from keyring related updates.  This causes each to run:

```
this.stopPolling();
await this.detectNfts();
this.intervalId = setInterval(...)
```

Because `detectNfts` is async, `intervalId` is still undefined.  So they each schedule their own interval without stopping a previous interval.

Fix: Only start/stop when relevant settings change.

### `@metamask/assets-controllers`

- **FIXED**: NFT detection running too many times

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Review by salimtb — DISMISSED** [review]

**Review by sahar-fehri — APPROVED** [review]

**Review by mcmire — COMMENTED** [review]
Are there any tests we can write to ensure that this doesn't occur again?

**Comment by bergeron** [comment]
> Are there any tests we can write to ensure that this doesn't occur again?

yes.  Let me write a test flipping some preferences and checking how many the HTTP route is called

**Review by mcmire — APPROVED** [review]
@bergeron Okay, cool. These tests are not in the best shape, and I'm noticing that there aren't any tests at all for when `useNftDetection` is set. This seems pretty important, so if you have to spend more than an hour on this, don't worry about it — we can add these tests later. From looking at the changes here, it makes sense that this would reduce the number of calls, so I'll approve it.

**Comment by bergeron** [comment]
Added a unit test that failed on the old code, and passes on the new code

**Review by mcmire — APPROVED** [review]
Glad you were able to figure it out. Nice and simple!

**Pull request merged**
