### PR TITLE
Add missing `json-rpc-{engine,middleware-stream}` CHANGELOG tag diff links

### PR DESCRIPTION
**Pull request by MajorLift**
## Background

While migrating `@metamask/json-rpc-engine` and `@metamask/json-rpc-middleware-stream` into the core repo, some earlier release commits that were untagged in the original repo (and didn't have CHANGELOG entries) were skipped by the tag porting script. These were created manually after the fact, and now they need to be added to the CHANGELOG as well. 

- Motivation: [#1802 (comment)](https://github.com/MetaMask/core/pull/1802#issuecomment-1791514273)

## Tasks

- [x] Tag diff links need to be added to the CHANGELOG for these manually-added tags.
  - `json-rpc-engine`: https://github.com/MetaMask/core/issues/2002#issuecomment-1800837972
  - `json-rpc-middleware-stream`: https://github.com/MetaMask/core/issues/2002#issuecomment-1804323662
- [x] Add empty CHANGELOG entries for these versions to satisfy `auto-changelog` validation.

## References

- Closes https://github.com/MetaMask/core/issues/2002

## Changelog

N/A

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by Gudahtt** [comment]
I might be missing something, but are these entries useful? I like that we have the tags now, but omitting these entries from the changelog might make sense given that we don't have any change entries to document

**Review by mcmire — DISMISSED** [review]
I'm fine with this. It looks like, however, that there are also missing tags for:

- 2.2.0: https://github.com/MetaMask/core/commit/286c2716a7b856b95f74d64edd9e653728dd031c
- 2.1.0: https://github.com/MetaMask/core/commit/93e2b7224f7370468466e2e5e29a2c10da016b11
- 2.0.0: https://github.com/MetaMask/core/commit/4909d7fd95a555a7ae18cb1f9840db4fe1f3c85d
- 1.0.0: https://github.com/MetaMask/core/commit/304f6efa4d1be2460c9d0bec48224cefcf7fd208

**Comment by MajorLift** [comment]
@Gudahtt `autochange-log` validation requires that version headings be present in the CHANGELOG for all of the versions in the tag diff links. 

I think the tags and tag diff links are definitely adding useful information and shouldn't be removed. Given that, to get rid of the placeholder version headings, I think we'll have to either remove the logic for matching tag diff links with version headings, or add an option to specify a range of versions that we should expect to be empty because the CHANGELOGs were never written.

**Comment by MajorLift** [comment]
@mcmire Thanks for finding those commits! I added tags + diff links for those in https://github.com/MetaMask/core/pull/2008/commits/13ce5ad8365c9c339f6f381573300161a5515168, and also found more early tags in `json-rpc-middleware-stream`.

**Comment by MajorLift** [comment]
I think just keeping the empty version headings might be useful, as they represent the full version history of the package, and the unwritten changelogs is also part of that history.

**Comment by Gudahtt** [comment]
We already don't have complete history of packages in our changelogs, as we didn't preserve changelogs from before we migrated `metamask-controller` to the `core` monorepo. Personally I'd look in at the tags in the repo if I wanted to dig into older releases, I would never look at the changelog for that. As such I wouldn't find these links useful. It's easy to navigate to the `compare` pages in GitHub if you know the tags.

I look at changelogs for additional high-level context about what each release consisted of, which is missing here.

**Comment by MajorLift** [comment]
In that case, seems like the way forward for package migrations would be: a) create the tags for untagged pre-migration releases, but b) not add them to the changelog?

I'm good with that so long as we can expect potential users of the package to look at the changelog as just a high-level overview of version history, instead of an exhaustive source of truth.

Although, it does seem like the empty-changelog tag diff links are equally as useful (or un-useful) as the existing tag diff links. Would it be worth modifying `autochange-log` so we can avoid potentially confusing users with a partial version history here (without having to add the empty version headings)? Of course, we can always get the complete version history from npm or `git ls-remote`, so I guess the question is whether our expected audience for the changelog file is internal only or external users as well.

**Comment by MajorLift** [comment]
I'm good with just closing this PR. So long as the tags are created, I don't think these changes are adding anything meaningful. We could always revisit this if there's confusion about the changelogs in the future. @Gudahtt @mcmire Would that be ok, or is there anything else you'd maybe like to address?

**Comment by Gudahtt** [comment]
Maybe we could leave a note about looking at the old archived repo to see the changelog for older releases? If you're concerned about this not being comprehensive, maybe that would be an effective way to fix that

**Comment by MajorLift** [comment]
The changelogs for these packages was created at [json-rpc-engine@5.2.0](https://github.com/MetaMask/core/commit/0a71be92574f76daeb194d14d9ad62ef0fe1cd19) and [json-rpc-middleware-stream@3.0.0](https://github.com/MetaMask/core/commit/09ee1574bc7a55b391ea3585f7c63b5a5f6e1081), so all of the versions before that don't have any changelog entries anywhere. 

No tag messages or tag diff links in the original repo, since these releases weren't tagged, and it seems no release commit messages, either. 

The tag diff compare links we now have in core are the only window we have into what was changed in these versions. Including them would be nice, but preserving the changelog starting point also makes sense to me.

**Comment by Gudahtt** [comment]
What I meant is that we could add this as a change entry:

```
### Changed
- See here for details: https://github.com/MetaMask/json-rpc-engine/blob/main/CHANGELOG.md
```

For `json-rpc-engine` for example

Either for every one of these blank releases, or once with a note about how it applies to all previous releases as well

**Comment by Gudahtt** [comment]
Given that these releases are ancient history and were never documented, closing this PR and leaving them undocumented would make sense to me.

**Comment by MajorLift** [comment]
Closing as WONTFIX

**Pull request closed without merging**
