### PR TITLE
refactor: remove global network from transaction controller

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## Explanation

Remove all global network usage from the `@metamask/transaction-controller` package.

Specifically:

- Remove the following constructor options:
  - `blockTracker`
  - `isMultichainEnabled`
  - `onNetworkStateChange`
  - `provider`
- Require `networkClientId` option in calls to `addTransaction`.
- Make `networkClientId` required in `TransactionMeta` type.
- Remove global instances of:
  - `PendingTransactionTracker`
  - `IncomingTransactionHelper`
  - `NonceTracker`.
- Replace `wipeTransactions` method arguments with object containing optional `chainId` and `address` properties.
- Require `networkClientId` argument in:
  - `getNonceLock`
  - `estimateGas`
  - `estimateGasBuffered`
- Remove `filterToCurrentNetwork` option from `getTransactions` method.
- Add `networkClientId` argument to `handleMethodData` method.
- Add `MethodDataHelper` to encapsulate `handleMethodData` method logic.
- Replace `getProvider` and `getEthQuery` methods with `getNetworkClient` method in `MultichainTrackingHelper`.
- Created nested debug loggers per chain in `PendingTransactionTracker` and `IncomingTransactionHelper`.
- Create dedicated debug logger for `MultichainTrackingHelper` with additional logs.

## References

* Related to [#3499](https://github.com/MetaMask/MetaMask-planning/issues/3499)
* [Extension Adoption PR](https://github.com/MetaMask/metamask-extension/pull/28449)
* [Mobile Adoption PR](https://github.com/MetaMask/metamask-mobile/pull/12321)

## Changelog

See `CHANGELOG.md`.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate
- [x] I've prepared draft pull requests for clients and consumer packages to resolve any breaking changes

### CODE REVIEW

**Comment by matthewwalsh0** [comment]
@metamaskbot publish-preview

**Comment by matthewwalsh0** [comment]
@metamaskbot publish-preview

**Comment by matthewwalsh0** [comment]
@metamaskbot publish-preview

**Comment by matthewwalsh0** [comment]
@metamaskbot publish-preview

**Review by pedronfigueiredo — APPROVED** [review]

**Review by OGPoyraz — DISMISSED** [review]
LGTM, thanks for detailed changes in the description.

**Review by OGPoyraz — DISMISSED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

**Review by pedronfigueiredo — APPROVED** [review]

**Comment by matthewwalsh0** [comment]
@metamaskbot publish-preview

**Pull request merged**
