### PR TITLE
Typing fixes for `TransactionController.test.ts`

### PR DESCRIPTION
**Pull request by MajorLift**
## Explanation

With the Transaction Controller under active development, it's important to ensure that its tests are valid. This PR improves typing in the tests by removing `any` usage and fixing `as` assertions, mainly by enforcing that `TransactionMeta` mock objects correctly conform to the type they're intended to test. 

Typing mock objects as `any` can be convenient for omitting required but non-essential properties, but it also keeps TypeScript from alerting us when objects with invalid shapes are being used for tests. If necessary, type assertions that don't use `any` e.g. `as TransactionMeta` are a much better compromise.

- Fixed test mock object typing:
  - `TransactionMeta` with failed status should contain an error property.
  - `from`, `to` should be located in the `txParams` property (or the mock object typed as `TransactionMeta & { from: Hex; to: Hex }`)
- Removed `any` usage that's become unnecessary (a key problem with `any` is that it doesn't tell you when it's no longer needed, and continues to suppress any changed or new errors).
- Changed `TransactionMeta` definition to equivalent but more readable expression.

## Changelog

N/A

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by mcmire** [comment]
Hi @matthewwalsh0 @vinistevam @OGPoyraz @blackdevelopa, a bit of context behind these changes. One of our goals is to ensure that throughout our packages we aren't using type assertions when we don't have to (particularly the use of `as any`). So this is where this PR is coming from. Would you be willing to review this PR when you get a chance? Thanks!

**Comment by OGPoyraz** [comment]
Hey @mcmire & @MajorLift 
Thank you so much for this PR, type changes @MajorLift make sense to me. 
Btw I was looking around the PRs and randomly saw this one, I know you already mentioned us but it's easy to miss such notifications in Github, would be awesome if you ping us directly in slack, thanks again 🙏

**Comment by MajorLift** [comment]
@OGPoyraz Will do! Thanks for the heads up.

**Review by OGPoyraz — APPROVED** [review]
Lgtm

**Pull request merged**
