### PR TITLE
Re-enable @typescript-eslint/consistent-type-definitions

### LINKED ISSUE #1932: Re-enable `@typescript-eslint/consistent-type-definitions`
There are 79 violations when we re-enable this rule. We need to convert all instances of `interface` to `type`, taking care to reverse cases in which interfaces are extending other interfaces (`A extends B` should come out to `B & A`).

### PR DESCRIPTION
**Pull request by mcmire**
## Explanation

This ESLint rule was disabled in a previous commit when our ESLint config packages were bumped, because it caused lint violations.

This commit re-enables this rule going forward. However, since fixing the lint violations by converting `interface`s to `type`s would cause breaking changes, this commit adds inline overrides to allow existing `interface`s to exist.

## References

Fixes #1932.

## Changelog

(No consumer-facing changes.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by mcmire** [comment]
Ah, you are right. Hmm. This makes me wonder why we chose to enforce type aliases instead of interfaces again. I will think about this.

**Comment by mcmire** [comment]
This is the commit in `eslint-config` when we enforced type aliases instead of interfaces: https://github.com/MetaMask/eslint-config/pull/216. There is a thread in chat which also talks about this (this might get eaten by the data retention gods eventually, but for now search for "TypeScript interfaces", then find a message by Erik on November 29, 2021). Apparently interfaces caused frustration because they prevented the `Json` type from being used effectively. I wonder whether the problem in question could have been solved a different way however.

**Comment by MajorLift** [comment]
Another reason to prefer types is that TypeScript interfaces don't support multiple inheritance, but type intersections can be freely combined without relying on workarounds.

**Review by MajorLift — APPROVED** [review]

**Comment by mcmire** [comment]
I rebased this branch, as the history somehow got corrupted after merging `main`. Now everything is in one commit.

I've addressed the existing violations by adding inline overrides instead of converting them to `type` (except in test files).

Ready for another review.

**Comment by mcmire** [comment]
Fixed merge conflicts.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
