### PR TITLE
refactor: remove retry validation

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## Explanation

When calling `speedUpTransaction` or `stopTransaction`, the existing gas fee values are increased by `10%` unless specific `gasValues` are provided.

If provided, these are validated to at least be an increase of `10%` over the existing values in the original transaction.

This validation has resulted in multiple errors due to scenarios such as:

- Only one of `maxFeePerGas` or `maxPriorityFeePerGas` was too low so it alone is increased via the UI, causing these validations to fail since the other value has not increased by at least `10%`.
- A transaction ultimately had sufficient gas fees but was below the market estimate so the validations also fail if this difference is less than `10%`.
- The clients do not currently gracefully handle this error meaning the user is unaware of the problem and why their cancel or speed up attempt failed.

This PR ultimately removes these validations so the controller can still automatically increase the previous gas fees if no new values are provided, however it is now the responsibility of the client to provide suitable values, and these are always respected.

In addition, to simplify the implementation and future maintenance of the fix, existing duplication between the `speedUpTransaction` and `stopTransaction` methods has been removed via a new `#retryTransaction` and `getTransactionParamsWithIncreasedGasFee` methods.

## References

Relates to [#25337](https://github.com/MetaMask/metamask-extension/issues/25337) [#2444](https://github.com/MetaMask/MetaMask-planning/issues/2444)

### `@metamask/transaction-controller`

- **CHANGED**: No longer validate increase of `gasValues` passed to `speedUpTransaction` and `stopTransaction` methods.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by matthewwalsh0** [comment]
@metamaskbot publish-preview

**Comment by matthewwalsh0** [comment]
@metamaskbot publish-preview

**Comment by matthewwalsh0** [comment]
@metamaskbot publish-preview

**Comment by jpuri** [comment]
Hey @matthewwalsh0 : PR is changing and at same time moving the code which makes hard to review.

**Comment by matthewwalsh0** [comment]
> Hey @matthewwalsh0 : PR is changing and at same time moving the code which makes hard to review.

The vast majority of changes are to remove the duplication, meaning the resulting logic should be identical except that `validateMinimumIncrease` is simply no longer called.

**Review by pedronfigueiredo — APPROVED** [review]

**Review by vinistevam — APPROVED** [review]

**Pull request merged**
