### PR TITLE
fix: transaction controller startup

### PR DESCRIPTION
**Pull request by matthewwalsh0**
## Explanation

Refactor the handling of incomplete transactions when initialising the `TransactionController`.

- `unapproved` transactions are now removed entirely and the `initApprovals` method has been removed.
  - Previously this `initApprovals` method allowed the clients to re-trigger approval requests and ultimately transaction confirmations.
  - This was only used in the extension, plus is a rare use case, since unapproved transactions are automatically rejected when closing the popup.
  - Unapproved transactions were never handled in mobile and resulted in error scenarios and unnecessary background requests.
- `approved` transactions are now marked as `failed`.
  - Previously approved transactions were automatically signed and submitted to support MV3.
  - This poses a potential security issue and undesired UX and is also a rare scenario.
- `signed` transactions are now marked as `failed`.
  - These transactions were not handled previously and appear to be the primary cause of [#23361](https://github.com/MetaMask/metamask-extension/issues/23361).

In addition:

- Remove `approveTransaction` flow in `PendingTransactionTracker`.
- Add updated `rawTx` to cancel and speed up transactions.
- Skip normalization and validation when marking transaction as failed.
- Fix transaction resubmit if a single transaction fails.

## References

Fixes [#23361](https://github.com/MetaMask/metamask-extension/issues/23361)

### `@metamask/transaction-controller`

- **BREAKING**: Remove `initApprovals` method.
- **BREAKING**: Remove `beforeApproveOnInit` hook.
- **CHANGED**: Remove `unapproved` transactions during initialisation.
- **CHANGED**: Fail `approved` and `signed` transactions during initialisation.

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by matthewwalsh0** [comment]
@metamaskbot publish-preview

**Comment by Gudahtt** [comment]
Thoughts on splitting this into multiple PRs? These changes seem like they would be easy to do separately, and seem unrelated to the initialization changes:
* CHANGED: Change getPermittedAccounts constructor callback to optional.
* ADDED: Add SPEED_UP_RATE, CHAIN_IDS, and ETHERSCAN_SUPPORTED_NETWORKS constants.

**Comment by matthewwalsh0** [comment]
> Thoughts on splitting this into multiple PRs? These changes seem like they would be easy to do separately, and seem unrelated to the initialization changes:
> 
> * CHANGED: Change getPermittedAccounts constructor callback to optional.
> * ADDED: Add SPEED_UP_RATE, CHAIN_IDS, and ETHERSCAN_SUPPORTED_NETWORKS constants.

I absolutely can if required. But they are each just one line changes so wanted to avoid the admin overhead.

**Comment by Gudahtt** [comment]
Since b both changes serve a distinct purpose, it would be preferred to make them separately even they are only 1-line changes, [as suggested by the contributor docs](https://github.com/MetaMask/contributor-docs/blob/main/docs/pull-requests.md#create-smaller-pull-requests).

Certainly these changes don't contribute much to the size of the PR, so they aren't problematic for that reason. But if we're reviewing the commit history to understand what changed, these would not appear. And similarly if we found a bug with the initialization refactor and wanted to revert it, it would also revert these two small changes unnecessarily, which is prevented by separating them.

**Review by pedronfigueiredo — APPROVED** [review]

**Review by OGPoyraz — APPROVED** [review]

**Pull request merged**
