### PR TITLE
improv: account syncing performance

### PR DESCRIPTION
**Pull request by mathieuartu**
## Explanation

This PR adds multiple improvements for the account syncing process, namely: 

- check if the account is of EVM type before saving it to user storage
- check if the account keyring type is either HD or simple
- wait for `AccountsController:accountAdded` event to fire before adding another account

## References

[NOTIFY-1158](https://consensyssoftware.atlassian.net/jira/software/projects/NOTIFY/boards/616?assignee=712020%3A5843b7e2-a7fe-4c45-9fbd-e1f2b2eb58c2&selectedIssue=NOTIFY-1158)

### `@metamask/profile-sync-controller`

- **FIXED**: various account syncing performance improvements and bug fixes. 
   - check if `isEvmAccountType` before saving an account in user storage in account syncing
   - check for correct `KeyringType` before saving an account in user storage in account syncing
   - wait for `AccountsController:accountAdded` event to fire before adding another account in account syncing

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate
- [x] I've prepared draft pull requests for clients and consumer packages to resolve any breaking changes

[NOTIFY-1158]: https://consensyssoftware.atlassian.net/browse/NOTIFY-1158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mathieuartu** [comment]
@metamaskbot publish-preview

**Comment by mathieuartu** [comment]
@metamaskbot publish-preview

**Comment by mathieuartu** [comment]
@metamaskbot publish-preview

**Comment by mathieuartu** [comment]
@metamaskbot publish-preview

**Comment by mathieuartu** [comment]
@metamaskbot publish-preview

**Comment by mathieuartu** [comment]
@metamaskbot publish-preview

**Review by matteoscurati — APPROVED** [review]
LGTM!

**Pull request merged**
