### PR TITLE
Compare selector return values deeply

### PR DESCRIPTION
**Pull request by mcmire**
## Explanation

Currently, it is difficult to use the messenger to subscribe to a subset of state changes by using the three-argument form of `ControllerMessenger.subscribe` — that is, passing a selector function. To be used effectively, the selector must return only one property in state and the value of that property must be a primitive. If either of these is not true — for instance, if the developer wishes to select more than one property in state, and so has the selector return an array of values rather than a single value — then the event listener will be fired for every state change. This occurs because we perform a shallow equality check when comparing the return value of the selector for the previous state change and the current return value of the selector. This commit replaces this with a deep equality check. The `just-compare` package is being used in order to avoid a dependency on Lodash, which is a rather large library, and add minimal size to the bundle instead.

## Changelog

(Updated in PR)

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Comment by Gudahtt** [comment]
Hmm, so this was somewhat of an intentional choice, though it definitely hasn't been documented well here.

The "selector function" here was assumed to act like a Reselect function, in that it would return the same instance if no data had changed. So a simple comparison check _would_ be correct, and much more efficient than a deep comparison.

There is a tradeoff here, because I can see this being an easy mistake to make even if we do document it correctly. But deep comparisons by default would negatively impact performance quite a bit for large pieces of data.

**Comment by mcmire** [comment]
@Gudahtt Hmm, could you go into more detail about what you mean?

As an example, let's say we had the following scenario:

``` suggestion
    this.messagingSystem.subscribe(
      'PreferencesController:stateChange',
      ({
        ipfsGateway,
        openSeaEnabled,
        isIpfsGatewayEnabled,
      }) => {
        const selectedAccount = this.messagingSystem.call(
          'AccountsController:getSelectedAccount',
        );

        const needsUpdateNftMetadata =
          (isIpfsGatewayEnabled && ipfsGateway !== '') || openSeaEnabled;

        if (needsUpdateNftMetadata && selectedAccount) {
          await this.#updateNftUpdateForAccount(selectedAccount);
        }
      },
    );
```

Because we're listening for any property of PreferencesController state to change, `#updateNftUpdateForAccount` may be called even when we don't want it to.

It seems like we _should_ be able to fix this by saying:

``` suggestion
    this.messagingSystem.subscribe(
      'PreferencesController:stateChange',
      ({
        ipfsGateway,
        openSeaEnabled,
        isIpfsGatewayEnabled,
      }) => {
        const selectedAccount = this.messagingSystem.call(
          'AccountsController:getSelectedAccount',
        );

        const needsUpdateNftMetadata =
          (isIpfsGatewayEnabled && ipfsGateway !== '') || openSeaEnabled;

        if (needsUpdateNftMetadata && selectedAccount) {
          await this.#updateNftUpdateForAccount(selectedAccount);
        }
      },
      (preferencesControllerState) => ({
        ipfsGateway: preferencesControllerState.ipfsGateway,
        openSeaEnabled: preferencesControllerState.openSeaEnabled,
        isIpfsGatewayEnabled: preferencesControllerState.isIpfsGatewayEnabled,
      }),
    );
```

But right now this wouldn't work because of the shallow equality check: the event handler would still get called every time PreferencesController state is changed.

Are you suggesting that you have another way to optimize this in mind?

**Comment by Gudahtt** [comment]
Yes; if you use a reselect selector, it will return the same object reference if the contents have not changed. This is the norm in a React/Redux context, which is where the idea for this selector function came from.

**Comment by mcmire** [comment]
@Gudahtt Hmm. So are you saying that this would eventually look like the following?

``` typescript
// === PreferencesController.ts ===

export const selectOpenSeaEnabled = (preferencesControllerState) =>
  preferencesControllerState.openSeaEnabled;

export const selectIpfsGateway = (preferencesControllerState) =>
  preferencesControllerState.ipfsGateway;

export const selectIsIpfsGatewayEnabled = (preferencesControllerState) =>
  preferencesControllerState.isIpfsGatewayEnabled;

// === Some other controller ===

import { createSelector } from 'reselect';
import {
  selectOpenSeaEnabled,
  selectIpfsGateway,
  selectIsIpfsGatewayEnabled
} from '@metamask/preferences-controller';

const selectPreferencesControllerState = createSelector(
  [
    selectOpenSeaEnabled,
    selectIpfsGateway,
    selectIsIpfsGatewayEnabled,
  ],
  (openSeaEnabled, ipfsGateway, isIpfsGatewayEnabled) => ({
    openSeaEnabled,
    ipfsGateway,
    isIpfsGatewayEnabled,
  })
)

class SomeOtherController {
  constructor() {
     this.messagingSystem.subscribe(
      'PreferencesController:stateChange',
      ({
        ipfsGateway,
        openSeaEnabled,
        isIpfsGatewayEnabled,
      }) => {
        const selectedAccount = this.messagingSystem.call(
          'AccountsController:getSelectedAccount',
        );

        const needsUpdateNftMetadata =
          (isIpfsGatewayEnabled && ipfsGateway !== '') || openSeaEnabled;

        if (needsUpdateNftMetadata && selectedAccount) {
          await this.#updateNftUpdateForAccount(selectedAccount);
        }
      },
      selectPreferencesControllerState,
    );
  }
}
```

**Comment by Gudahtt** [comment]
Yes, exactly. Note as well that immer stores also have this property; for example even the simple selector `(networkState) => networkState.networkConfigurations` would not require any deep equals comparison because an object reference comparison is equivalent due to how immer handles state updates. The two systems work together.

We can have correct and fast state subscriptions across the entire stack if we commit to updating state immutably, and using memoized selectors to access that state.

**Comment by Gudahtt** [comment]
Perhaps we could solve this by adding an optional parameter for an alternative comparator. That's how Reselect handles these cases as well I believe.

**Comment by mcmire** [comment]
@Gudahtt I don't mind using ~shallow~ reference equality if it's the way we want to go. You said this already, but I am also slightly concerned that there will be some initial confusion on how to use selectors, and we may have to give more specific examples for controllers. Continuing with the example I gave, it seems that you would need to make sure that if you want to subscribe to changes in multiple properties from state within a controller, you would need to make sure that you've first written selector functions that either access a single property from state or return a primitive value, and then you can pass them to `createSelector`.

In other words, if someone were to attempt to write this:

``` typescript
// === Some other controller ===

import { createSelector } from 'reselect';
import type { PreferencesState } from '@metamask/preferences-controller';

const selectPreferencesControllerState = createSelector(
  [(preferencesControllerState: PreferencesState) => state],
  (preferencesControllerState) => ({
    openSeaEnabled: preferencesControllerState.openSeaEnabled,
    ipfsGateway: preferencesControllerState.ipfsGateway,
    isIpfsGatewayEnabled: preferencesControllerState.isIpfsGatewayEnabled,
  })
);

class SomeOtherController extends BaseController {
  constructor() {
     this.messagingSystem.subscribe(
      'PreferencesController:stateChange',
      ({
        ipfsGateway,
        openSeaEnabled,
        isIpfsGatewayEnabled,
      }) => {
        // ...
      },
      selectPreferencesControllerState,
    );
  }
}
```

...this would not work, because the output selector passed to `createSelector` would return a different object each time `selectPreferencesControllerState` is called.

Is this your expectation as well, that this would be incorrect?

**Comment by Gudahtt** [comment]
Yes that sounds right. But despite the risks I don't think we should make the performance tradeoff. Thoughts on allowing an optional alternative comparator?

**Comment by mcmire** [comment]
Sure. I'll go ahead and close this PR and add a comparator option in a new PR.

**Pull request closed without merging**
