### PR TITLE
Update token rates controller for multi evm fetching

### PR DESCRIPTION
**Pull request by bergeron**
## Explanation

This PR Updates the `TokenRatesController` to be used in clients across multiple chains.

## References

* Related to [#67890](https://github.com/MetaMask/metamask-extension/pull/28158)

### `@metamask/assets-controllers`

- **CHANGED**: When the `TokensController:stateChange` subscription is fired, token prices are now updated across all chain IDs whose tokens changed, instead of just the current chain. 

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate
- [ ] I've prepared draft pull requests for clients and consumer packages to resolve any breaking changes

### CODE REVIEW

**Comment by bergeron** [comment]
@metamaskbot publish-preview

**Comment by bergeron** [comment]
@metamaskbot publish-preview

**Comment by bergeron** [comment]
@metamaskbot publish-preview

**Comment by bergeron** [comment]
Gonna tweak the changelog.  Since `fetchAndMapExchangeRatesForUnsupportedNativeCurrency` is a private function that is not exported or used elsewhere, I don't think it needs to be in the changelog since it won't affect consumers

**Review by sahar-fehri — APPROVED** [review]

**Pull request merged**
