### PR TITLE
Remove `NotificationController`

### PR DESCRIPTION
**Pull request by hmalik88**
Removes the `NotificationController` in favor of `NotificationServicesController`, see https://github.com/MetaMask/core/pull/4809

### CODE REVIEW

**Review by MajorLift — DISMISSED** [review]
LGTM!

**Comment by Prithpal-Sooriya** [comment]
RIP 🥲

**Comment by Prithpal-Sooriya** [comment]
The @MetaMask/notifications team will align with the @MetaMask/snaps team on this.

Our notifications team were preparing the "notification unification" in Q1 (unify snaps, confirmations, our back-end notifications, and future notifications or alerts), but, as this seems to be moving forward, we can expedite it 😅.

We can have a brainstorm and discussion on how we can create a unified/orchestrated notification controller that:
1. Allows other teams to manage and own their own notifications. Make it easy to contribute and extend.
2. Create a clean/minimal interface that reflects 1:1 with the UI
3. Prevent god controllers (e.g. a notification controller that becomes too large and hard to manage, our team is already starting to feel this as we are planning to release more and more notifications).

This can be done in iterative steps. I'm just bringing this up as the current `NotificationServicesController` is very large, very complex, has confusing method names, and is getting harder and harder to extend.

**Review by MajorLift — APPROVED** [review]

**Review by FrederikBolding — APPROVED** [review]
RIP🫡

**Pull request merged**
