### PR TITLE
Refactor controllers to use `"getState"` action, `"stateChange"` event types defined in `base-controller`

### PR DESCRIPTION
**Pull request by MajorLift**
## Motivation

- The `"getState"` action and `"stateChange"` event are defined in `base-controller`, and are common to all controllers. 
- https://github.com/MetaMask/core/pull/1890 defines polymorphic types `ControllerGetStateAction` and `ControllerStateChangeEvent`.

## Explanation

- This PR refactors all controllers in core so that their respective `"getState"` action and `"stateChange"` event types are defined using the `ControllerGetStateAction` and `ControllerStateChangeEvent` types from `base-controller`.
- The redefined type definitions are exactly equivalent to the previous typings with no breaking changes introduced.

## Impact

- This accomplishes code de-duplication.
- It makes it possible to propagate any future updates to these types from a single source. 
- All controllers now expect a `"getState"` action and a `"stateChange"` event, and can accept them without requiring type casting in `base-controller`.
- `immer` can now be removed as a dependency from 7 packages.

## References

- Extracted from https://github.com/MetaMask/core/pull/1890

### `@metamask/base-controller`
- **ADDED**: Exports `ControllerGetStateAction`, `ControllerStateChangeEvent` types

## Checklist

- [x] I've updated the test suite for new or updated code as appropriate
- [x] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [x] I've highlighted breaking changes using the "BREAKING" category above as appropriate

### CODE REVIEW

**Review by mcmire — APPROVED** [review]
Looks good!

**Comment by MajorLift** [comment]
@mcmire I removed some changes in `network-controller` that were irrelevant to the scope of this PR (replacing string literal controller names with dynamic template strings).

**Review by mcmire — APPROVED** [review]
LGTM.

**Comment by Gudahtt** [comment]
Maybe better to wait until after v91 is merged before merging this, to avoid complicating that release

**Review by Mrtenz — APPROVED** [review]

**Comment by MajorLift** [comment]
@Gudahtt Good call! Holding off for now.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
